package UI;

import logic.Profile;
import controller.Controller;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Locale;

public class LogInOrCreateFrame extends JFrame {

    JFrame thisFrame = null;
    protected JPanel accountCreateForm;
    private JButton newAccountButton;
    private JButton logInButton;
    private JLabel loginLabel;
    private JLabel newAccountLabel;
    private JButton backButton;
    private Controller controller = new Controller();
    private ArrayList<Profile> profiles = controller.getProfiles();

    public LogInOrCreateFrame(JFrame previousFrame) {

        setTitle("Log in to Existing Account or Create Accounts");
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        //to go back to the previous frame
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                previousFrame.setVisible(true);
            }
        });

        //goes to login page
        //TODO complete the login panel (its gonna be selecting a profile an choosing its location
        logInButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (controller.getProfiles().isEmpty()) {
                    NoProfilesLoginFrame nextFrame = new NoProfilesLoginFrame(thisFrame);
                    nextFrame.setVisible(true);
                    dispose();
                } else {
                    ProfilesLoginFrame nextFrame = new ProfilesLoginFrame(thisFrame, controller.getProfiles());
                    nextFrame.setVisible(true);
                    nextFrame.setLocationRelativeTo(null);
                    dispose();
                }

                //TODO switch content pane OR new frame?
//                accountCreateForm.setVisible(false);
//                accountCreateForm.removeAll();
//                JPanel Login = new JPanel();
//                Login.add(new JLabel("Username") );
//                Login.add(new JTextField());
//
//                accountCreateForm.add(Login);
//                accountCreateForm.setVisible(true);
            }
        });

        //goes to account creation page
        newAccountButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ProfilesCreationFrame nextFrame = new ProfilesCreationFrame(thisFrame);
                nextFrame.setVisible(true);
                dispose();
//                accountCreateForm.setVisible(false);
//                accountCreateForm.removeAll();
//                JPanel createPanel = new ProfilePanel(thisFrame);
//                JLabel testing = new JLabel("SET UP ACCOUNTS");
//                testing.setFont(new Font(Font.SERIF, Font.BOLD, 20));
//                accountCreateForm.add(createPanel);
//                accountCreateForm.setVisible(true);
//                createPanel.setSize(900,400);
            }
        });

        thisFrame = this;
        add(accountCreateForm);
        setSize(600, 600);
        setLocationRelativeTo(null);
        //setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        accountCreateForm = new JPanel();
        accountCreateForm.setLayout(new GridBagLayout());
        accountCreateForm.setBackground(new Color(-4931890));
        loginLabel = new JLabel();
        Font loginLabelFont = this.$$$getFont$$$("Baghdad", Font.BOLD, 22, loginLabel.getFont());
        if (loginLabelFont != null) loginLabel.setFont(loginLabelFont);
        loginLabel.setForeground(new Color(-16777216));
        loginLabel.setText("Log in to an existing account");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.SOUTH;
        accountCreateForm.add(loginLabel, gbc);
        newAccountLabel = new JLabel();
        Font newAccountLabelFont = this.$$$getFont$$$("Baghdad", Font.BOLD, 22, newAccountLabel.getFont());
        if (newAccountLabelFont != null) newAccountLabel.setFont(newAccountLabelFont);
        newAccountLabel.setForeground(new Color(-16777216));
        newAccountLabel.setText("Create a new account");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridheight = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.SOUTH;
        accountCreateForm.add(newAccountLabel, gbc);
        newAccountButton = new JButton();
        newAccountButton.setBorderPainted(true);
        newAccountButton.setMargin(new Insets(10, 10, 10, 10));
        newAccountButton.setText("Create Account");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.gridheight = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        accountCreateForm.add(newAccountButton, gbc);
        logInButton = new JButton();
        logInButton.setBorderPainted(true);
        logInButton.setContentAreaFilled(true);
        logInButton.setMargin(new Insets(10, 10, 10, 10));
        logInButton.setText("Log in");
        logInButton.setVisible(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        accountCreateForm.add(logInButton, gbc);
        backButton = new JButton();
        backButton.setText("<-- Back");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.SOUTHWEST;
        accountCreateForm.add(backButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return accountCreateForm;
    }
}
